# Generated by Django 5.2.4 on 2025-08-11 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0003_alter_article_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='publisher_subscribers', to='news.publisher'),
        ),
    ]
